### ISSUE TITLE
Cant Save

### ISSUE THREAD

**Issue by RedxYeti** [Nicolas-Constanty/WillowTreeBLDEnhanced#4]
i can open up the files but i cant save them. win10 pro

edit* version 2.3.2

heres my log file

System.ArgumentNullException: Value cannot be null.
Parameter name: buffer
   at System.IO.BinaryWriter.Write(Byte[] buffer)
   at WillowTree.WillowSaveGame.WriteBankEntry(BinaryWriter bw, BankEntry entry, ByteOrder Endian, Int32 version)
   at WillowTree.WillowSaveGame.WriteWSG()
   at WillowTree.WillowSaveGame.SaveWSG(String filename)
   at WillowTree.WillowTreeMain.SaveToFile(String filename)
   at WillowTree.WillowTreeMain.Save_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at WillowTree.Program.Main()

**Comment by RedxYeti** [comment]
i noticed you asked for a the save in another thread, heres the save causing this error.

its an imported save from the OG game
[Save0005.zip](https://github.com/Nicolas-Constanty/WillowTreeBLDEnhanced/files/3056777/Save0005.zip)

**Comment by Nicolas-Constanty** [comment]
Thank RedxYeti. That work with the 2.3.3
